#!/bin/bash
# -----------------------------------------------------------------------
#   Fetch Clear and XanMod kernel sources.
#
#   Author: Mario Roy - http://github.com/marioroy
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, version 2 or later of the License.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------

if [[ "$1" == "all" ]]; then
    bash "$0" "clear" || exit $?
    bash "$0" "edge"  || exit $?
    bash "$0" "main"  || exit $?
    bash "$0" "lts"   || exit $?
    bash "$0" "rt"    || exit $?
    exit 0
fi

cl_url="https://cdn.download.clearlinux.org/releases"
xm_url="https://github.com/xanmod/linux/archive/refs/tags"

function fetch {
    local cl_rel="$1"
    local cl_file="$2"
    local xm_file="$3"

    mkdir -p "SOURCES" && cd "SOURCES" || exit 1

    if [[ ! -s "$cl_file" ]]; then
        rm -f cmdline config ./*.patch ./*.patch.xz ./*.spec ./*.tar.xz linux-*.src.rpm
        if [[ "$xm_file" == *6.8.[0-9]* && -e "../../rpmbuild.clear/SOURCES/$cl_file" ]]; then
            cp -a "../../rpmbuild.clear/SOURCES/$cl_file" .
        elif [[ "$xm_file" == *-rt* && -e "../../rpmbuild.main/SOURCES/$cl_file" ]]; then
            cp -a "../../rpmbuild.main/SOURCES/$cl_file" .
        else
            wget "${cl_url}/${cl_rel}/clear/source/SRPMS/${cl_file}"
        fi
        rpm2cpio "$cl_file" | cpio -i -d -u 2>/dev/null
    fi

    if [[ -n "$xm_file" && ! -s "$xm_file" ]]; then
        rm -f [0-9]*-xanmod*.tar.gz
        wget "${xm_url}/${xm_file}"
    fi
}

case "$1" in
    clear )
        cd "rpmbuild.clear" || exit 1
        echo "Fetching sources for Clear Native."
        fetch "41280" "linux-6.8.1-1419.src.rpm"
        ;;
    edge )
        cd "rpmbuild.edge" || exit 1
        echo "Fetching sources for XanMod Edge."
        fetch "41280" "linux-6.8.1-1419.src.rpm" "6.8.1-xanmod1.tar.gz"
        ;;
    main )
        cd "rpmbuild.main" || exit 1
        echo "Fetching sources for XanMod Main."
        fetch "41270" "linux-ltscurrent-6.6.8-1394.src.rpm" "6.6.22-xanmod1.tar.gz"
        ;;
    lts )
        cd "rpmbuild.lts" || exit 1
        echo "Fetching sources for XanMod LTS."
        fetch "41270" "linux-ltsprev-6.1.69-1331.src.rpm" "6.1.77-xanmod1.tar.gz"
        ;;
    rt )
        cd "rpmbuild.rt" || exit 1
        echo "Fetching sources for XanMod RT."
        fetch "41270" "linux-ltscurrent-6.6.8-1394.src.rpm" "6.6.21-rt26-xanmod1.tar.gz"
        ;;
    * ) echo "synopsis"
        echo "   $0 all | clear | edge | main | lts | rt"
esac

