#!/bin/bash
# -----------------------------------------------------------------------
#   Fetch kernel sources.
#   Author: Mario Roy - http://github.com/marioroy
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, version 2 or later of the License.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------

cl_rel="42470" cl_file="linux-6.11.3-1472.src.rpm"
kn_file="linux-6.11.3.tar.xz"

cl_url="https://cdn.download.clearlinux.org/releases"
kn_url="https://cdn.kernel.org/pub/linux/kernel/v6.x"

function fetch {
    mkdir -p "SOURCES" && cd "SOURCES" || exit 1

    if [[ ! -s "$cl_file" ]]; then
        # purge src.rpm files
        rm -f cmdline config ./*.patch ./*.patch.xz ./*.spec ./*.tar.xz linux-*.src.rpm
        wget "${cl_url}/${cl_rel}/clear/source/SRPMS/${cl_file}" || exit 1

        # extract src.rpm files
        rpm2cpio "$cl_file" | cpio -i -d -u 2>/dev/null
    fi

    if [[ ! -s "$kn_file" ]]; then
        rm -f linux-[0-9]*.tar.xz
        wget "${kn_url}/${kn_file}" || exit 1
    fi
}

echo "Fetch kernel sources"
cd ./rpmbuild || exit 1
fetch

echo "done."

