#!/bin/bash
# -----------------------------------------------------------------------
#   Fetch kernel sources.
#   Author: Mario Roy - http://github.com/marioroy
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, version 2 or later of the License.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------

if [[ "$1" == "all" ]]; then
    bash "$0" "clear" || exit $?
    bash "$0" "edge"  || exit $?
    exit 0
fi

cl_url="https://cdn.download.clearlinux.org/releases"
xm_url="https://github.com/xanmod/linux/archive/refs/tags"

function fetch {
    local cl_rel="$1"
    local cl_file="$2"
    local xm_file="$3"

    mkdir -p "SOURCES" && cd "SOURCES" || exit 1

    if [[ ! -s "$cl_file" ]]; then
        # purge src.rpm files
        rm -f cmdline config ./*.patch ./*.patch.xz ./*.spec ./*.tar.xz linux-*.src.rpm

        if [[ -z "$xm_file" && -e "../../rpmbuild.edge/SOURCES/$cl_file" ]]; then
            # refresh clear: copy src.rpm from edge folder
            cp -a "../../rpmbuild.edge/SOURCES/$cl_file" .
        elif [[ -n "$xm_file" && -e "../../rpmbuild.clear/SOURCES/$cl_file" ]]; then
            # refresh edge: copy src.rpm from clear folder
            cp -a "../../rpmbuild.clear/SOURCES/$cl_file" .
        else
            # otherwise, fetch src.rpm from the web
            wget "${cl_url}/${cl_rel}/clear/source/SRPMS/${cl_file}"
        fi

        # extract src.rpm files
        rpm2cpio "$cl_file" | cpio -i -d -u 2>/dev/null
    fi

    if [[ -n "$xm_file" && ! -s "$xm_file" ]]; then
        rm -f [0-9]*-xanmod*.tar.gz
        wget "${xm_url}/${xm_file}"
    fi
}

case "$1" in
    clear )
        cd "rpmbuild.clear" || exit 1
        echo "Fetching sources for Clear Native."
        fetch "41280" "linux-6.8.1-1419.src.rpm"
        ;;
    edge )
        cd "rpmbuild.edge" || exit 1
        echo "Fetching sources for XanMod Edge."
        fetch "41280" "linux-6.8.1-1419.src.rpm" "6.8.1-xanmod1.tar.gz"
        ;;
    * ) echo "synopsis"
        echo "   $0 all | clear | edge"
esac

