#!/bin/bash
# -----------------------------------------------------------------------
#   Purge packages.
#   Author: Mario Roy - http://github.com/marioroy
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, version 2 or later of the License.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------

for pkg in $(
    rpm -qa | grep -E "^linux-xm(bore|clear|echo|edge)" |\
              grep -Ev "(license|extra|dev|cpio)"
); do
    dir=$( rpm -ql "$pkg" | grep "modules" | head -1 )

    # The "clr-boot-manager update" command removes older kernel version.
    # Purge packages for kernels no longer present in /usr/lib/modules/.

    if [[ ! -e "$dir" ]]; then
        v=${pkg#*-}; v=${v#*-}; [[ "$v" == *"rt-"* ]] && v=${v#*-}
        p=${pkg%-*}; p=${p%-*}
        # Uninstall the packages separately.
        echo "Purging ${pkg}"
        ( sudo rpm -e "${p}-cpio-${v}"
          sudo rpm -e "${p}-dev-${v}"
          sudo rpm -e "${p}-extra-${v}"
          sudo rpm -e "${p}-${v}"
          sudo rpm -e "${p}-license-${v}"
        ) 2>/dev/null
    fi
done

